name: Deploy Keystone

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 156.38.217.108
          username: henridewitt
          key: ${{ secrets.KEYSTONE_SSH_KEY }}
          script: |
           script: |
           cd /var/www/keystone
           GIT_SSH_COMMAND='ssh -i /home/henridewitt/.ssh/keystone_deploy_key -o IdentitiesOnly=yes' git fetch origin main
           git reset --hard origin/main
           sudo -n systemctl restart keystone.service
